### ISSUE TITLE
Admin password is being logged in browser console.

### ISSUE THREAD

**Issue by troggy** [37coins/37coins-web#50]
That's not good :)

**Comment by Gateway85** [comment]
Hey. Can we have more details on when this is happening in order to reproduce?

**Comment by mahmed0715** [comment]
What can we do is: we can store the base64 ed credentials, 
currently we are storing {user,pass} raw, then when a request needs the Authorization header to be added, it then converts {user,pass} to base64 stirng.
we can store directly the base64 of {user,pass} so that no raw password can be found.

**Comment by troggy** [comment]
It might be my own local issue with KeePass browser extension. If you
cannot eproduce it and there are no corresponding console.log in the code,
just close it. Have a nice day!

**Comment by mahmed0715** [comment]
there is no console.log but we can see the password stored in sessionStorage or model.
So how i solved it, we dont store the password directly: we storing the encoded base 64 user:pass to sessionStorage and model. so that no one can see the password.
 its already done(adding this functionality to the Backbone.BasicAuth bower module)
one  question is: does window.Android.setConfig() extremely needing the password?  this is the only one where the password is direct called.

**Comment by troggy** [comment]
I know nothing about this client side code. The only thing I know for sure
is that there is no point to encode password to base64 as it could be
decoded easily. On the different note I doubt that this backbone app ever
need to store this password.

**Comment by Gateway85** [comment]
Did I understand correctly that the password is probably not needed and we can through it out altogether?

**Comment by mahmed0715** [comment]
the Authorization header need to add to header before a call server api, thus the user:pass needed.
Yeah i think so: the base64 can be decoded so no need to store as base64, the previous one {user,pass} is okay then.
But the backbone app needs to store password so that it can add to Authorization 
header ..

**Comment by mahmed0715** [comment]
Password needed actually. But the issue doesnt matter. so no change needed. 
We can stop this.

**Comment by johannbarbie** [comment]
this is standard basic authentication over SSL: http://en.wikipedia.org/wiki/Basic_access_authentication

nothing to be done -> close
